[tools]
"aqua:ast-grep/ast-grep" = "latest"
"aqua:atuinsh/atuin" = "latest"
"aqua:sharkdp/bat" = "latest"
bun = "latest"
"aqua:anthropics/claude-code" = "latest"
"aqua:openai/codex" = "latest"
"aqua:eza-community/eza" = { version = "v0.23.5", os = ["linux"] }
"aqua:sharkdp/fd" = "latest"
"github:entireio/cli" = { version = "v0.10.4-nightly.202608290622.a918e75fb", filter_bins = ["entire", "git-remote-entire"] }
"aqua:junegunn/fzf" = "latest"
"aqua:cli/cli" = "latest"
"aqua:git-lfs/git-lfs" = "latest"
"aqua:gitleaks/gitleaks" = "latest"
go = "latest"
"aqua:jdx/hk" = "latest"
"aqua:jqlang/jq" = "latest"
node = "latest"
"npm:@mariozechner/pi-coding-agent" = "latest"
"aqua:pnpm/pnpm" = "latest"
"aqua:BurntSushi/ripgrep" = "latest"
"aqua:tldr-pages/tlrc" = "latest"
"aqua:tmux/tmux-builds" = "latest"
"aqua:vi/websocat" = "latest"
"aqua:ajeetdsouza/zoxide" = "latest"
