min_version = "2026.8.16"

[settings]
idiomatic_version_file_enable_tools = ["node"]
trusted_config_paths = ["~/.codex", "~/.dotfiles", "~/Projects"]

[settings.npm]
package_manager = "npm"

[env]
HK_PKL_BACKEND = "pklr"
HK_MISE = "1"
