if [[ -n "${MACHINE_PLATFORM_SHELL_INITIALIZED:-}" ]]; then
  return 0
fi
MACHINE_PLATFORM_SHELL_INITIALIZED=1

export ENTIRE_TOKEN_STORE=file

MACHINE_PACKAGE_PREFIX=/home/linuxbrew/.linuxbrew
export PATH="$MACHINE_PACKAGE_PREFIX/bin:$MACHINE_PACKAGE_PREFIX/sbin:$PATH"
